### ISSUE TITLE
A lot of dropped frames and lagging

### ISSUE THREAD

**Issue by misiekkb** [Tsubajashi/mpv-settings#6]
Hi, 

I checked your config with yours harder on MacBook Pro 2019 1.4Ghz and I have very lagging and a lot of dropped frames, not matters which I choose shaders profile, or when I change ravu-zoom-r3 to ravu-r3, or lower r. 
I only fixed this when I turn off hidpi-window-scale, when I use autofit or geometry I have this same with turn on hidpi, a lot of dropped.
You write testing on Macbook Pro 13 2018, but this macbook have weaker CPU. Maybe you know how fixing this with shader?

BTW. grain.glsl make blue video screen.

**Comment by Tsubajashi** [comment]
the config was tested with its standard profile=video-mac setting, where it shouldnt drop frames.
About shader: they do not need a faster cpu, they are mostly on GPU. thats why i havent tested those on my macbook, as i wanted to just improve the quality a bit, since the displays are so nice.
im currently working on new shaders which should also completely work with macbooks.

**Comment by misiekkb** [comment]
Very thanks for answer. On my MacBook Pro your profile=video-mac are good without shader.

**Comment by Tsubajashi** [comment]
Perfect.
i will check out when its possible to use shaders with macs, i may wait for a future update on the moltenvk backend for macs.
you can close the issue if you want to, as its a low-ish priority to work on them until moltenvk becomes a thing
